### ISSUE TITLE
org.iq80.leveldb.impl.DbImpl$BackgroundProcessingException: java.lang.NullPointerException: array is null

### ISSUE THREAD

**Issue by subes** [pcmind/leveldb#9]
And this is another test that is failing inside another project of mine:

https://github.com/subes/invesdwin-context-persistence/blob/pcman-leveldb-error/invesdwin-context-persistence-parent/invesdwin-context-persistence-timeseries/src/test/java/de/invesdwin/context/persistence/timeseries/DatabasePerformanceTest.java

Here is the full stacktrace:

```
org.iq80.leveldb.impl.DbImpl$BackgroundProcessingException: java.lang.NullPointerException: array is null
	at org.iq80.leveldb.impl.DbImpl.checkBackgroundException(DbImpl.java:518)
	at org.iq80.leveldb.impl.DbImpl.writeInternal(DbImpl.java:914)
	at org.iq80.leveldb.impl.DbImpl.write(DbImpl.java:861)
	at ezdb.leveldb.EzLevelDbBatch.flush(EzLevelDbBatch.java:41)
	at de.invesdwin.context.persistence.timeseries.ezdb.ADelegateRangeTable$RangeBatchFinalizer.clean(ADelegateRangeTable.java:664)
	at de.invesdwin.util.lang.finalizer.AFinalizer.close(AFinalizer.java:56)
	at de.invesdwin.context.persistence.timeseries.ezdb.ADelegateRangeTable$DelegateRangeBatch.close(ADelegateRangeTable.java:637)
	at de.invesdwin.context.persistence.timeseries.DatabasePerformanceTest.testLevelDbPerformance(DatabasePerformanceTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.NullPointerException: array is null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.iq80.leveldb.util.Slice.<init>(Slice.java:61)
	at org.iq80.leveldb.table.CustomUserComparator.findShortestSeparator(CustomUserComparator.java:42)
	at org.iq80.leveldb.impl.InternalUserComparator.findShortestSeparator(InternalUserComparator.java:57)
	at org.iq80.leveldb.table.TableBuilder.add(TableBuilder.java:136)
	at org.iq80.leveldb.impl.DbImpl.buildTable(DbImpl.java:1301)
	at org.iq80.leveldb.impl.DbImpl.writeLevel0Table(DbImpl.java:1258)
	at org.iq80.leveldb.impl.DbImpl.compactMemTable(DbImpl.java:1218)
	at org.iq80.leveldb.impl.DbImpl.backgroundCompaction(DbImpl.java:561)
	at org.iq80.leveldb.impl.DbImpl.backgroundCall(DbImpl.java:530)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by subes** [comment]
Notice that this is a branch called pcman-leveldb-error which you have to checkout to debug this. Only there the 1.0 version of your fork is used.

**Comment by pcmind** [comment]
The implementation of `DBComparator#findShortestSeparator(byte[], byte[])` you are using (EzLevelDbComparator!?) is incorrect, it returns `null` where it should return a non `null` value; **start** for instance like mentioned in javadoc.

A more useful message/error can be thrown early, but ultimately the implementation used of DBComparator must be fixed.

**Comment by subes** [comment]
Thanks a lot here as well. This was indeed wrong. All tests are green now. And performance is a lot better than with leveldbjni!
